In [1]:
import argparse as ap
import cv2
import numpy as np
import os
from sklearn.externals import joblib
from scipy.cluster.vq import *

from sklearn import preprocessing
import math

In [38]:
des_list, image_paths = joblib.load('pkl/des_list_{}.pkl'.format('rumor'))

In [39]:
len(image_paths)

10664

In [40]:
len(des_list)

10555

In [41]:
for image_path, descriptor in des_list:
    if descriptor is None:
        des_list.remove((image_path, descriptor))

des_sum = 0
for image_path, descriptor in des_list:
    des_sum += descriptor.shape[0]

In [42]:
des_sum

9216844

In [43]:
len(des_list)

10547

In [44]:
# Stack all the descriptors vertically in a numpy array
descriptors = des_list[0][1]
for image_path, descriptor in des_list[1:]:
    descriptors = np.vstack((descriptors, descriptor))

KeyboardInterrupt: 

In [8]:
descriptors.shape

(497966, 128)

## Test

In [60]:
a = np.array([[1,2,3,4,5], [5,4,3,2,1]])
b = np.zeros((5,5))

In [61]:
b

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [62]:
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [63]:
b[0:2] = a

In [64]:
b[2:4] = a

In [65]:
len(a)

2

In [66]:
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 5.,  4.,  3.,  2.,  1.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 5.,  4.,  3.,  2.,  1.],
       [ 0.,  0.,  0.,  0.,  0.]])