In [2]:
from sklearn.externals import joblib
import random
import numpy as np

# 统计结果

In [19]:
certify_num_of_event, result_index_of_event = joblib.load('file/pkl/result.pkl')
event_features_list = joblib.load('file/pkl/event_features.pkl')

In [20]:
result_index_list = list(result_index_of_event.values())

In [21]:
result_0 = sum([len(x[0]) for x in result_index_list])
result_1 = sum([len(x[1]) for x in result_index_list])
result_2 = sum([len(x[2]) for x in result_index_list])

In [22]:
print('{} = {} : {} : {} = {:.1f} : {:.1f} : {}'.format(result_0+result_1+result_2, result_0,result_1,result_2,result_0/result_2, result_1/result_2,1))

35358 = 29209 : 4857 : 1292 = 22.6 : 3.8 : 1


## 统计图片数量

In [23]:
result_pic_num_list = []
for index, result in result_index_of_event.items():
    pic_num = 0
    
    event_features = event_features_list[index]
    for certify_list in result:
        for i in certify_list:
            pic_num += event_features['pic_num'][i]
    
    result_pic_num_list.append(pic_num)

In [24]:
sum(result_pic_num_list)

38550

In [25]:
certify_num_of_event[0]

[6, 1, 0]

In [26]:
result_index_of_event[0]

[[14, 9, 5, 16, 11, 7], [1], []]

In [27]:
event_features_list[0]

{'certify_0': [0, 5, 6, 7, 9, 10, 11, 14, 15, 16, 18],
 'certify_1': [1, 8],
 'certify_2': [2, 3, 4, 12, 13, 17],
 'id': 'CE04BFD3766B3D6BAA454A4F9DE8BCAD1458697553928',
 'pic_num': [0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1],
 'pic_num_0': [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1],
 'pic_num_1': [0, 1],
 'pic_num_2': [1, 1, 1, 1, 1, 1],
 'weibo_num': 19}

In [28]:
result_pic_num_list[0]

3

# TF-IDF

In [14]:
# coding:utf-8
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [3]:
#语料
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
]
#将文本中的词语转换为词频矩阵
vectorizer = CountVectorizer()
#计算个词语出现的次数
X = vectorizer.fit_transform(corpus)
#获取词袋中所有文本关键词
word = vectorizer.get_feature_names()

In [13]:
print(len(word))
word

9


['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [9]:
X.shape

(4, 9)

In [19]:
X.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [15]:
transformer = TfidfTransformer()
tfidf = transformer.fit_transform(X)

In [18]:
tfidf.toarray()

array([[ 0.        ,  0.43877674,  0.54197657,  0.43877674,  0.        ,
         0.        ,  0.35872874,  0.        ,  0.43877674],
       [ 0.        ,  0.27230147,  0.        ,  0.27230147,  0.        ,
         0.85322574,  0.22262429,  0.        ,  0.27230147],
       [ 0.55280532,  0.        ,  0.        ,  0.        ,  0.55280532,
         0.        ,  0.28847675,  0.55280532,  0.        ],
       [ 0.        ,  0.43877674,  0.54197657,  0.43877674,  0.        ,
         0.        ,  0.35872874,  0.        ,  0.43877674]])

In [20]:
tfidf.shape

(4, 9)

## 分词

In [22]:
import jieba

In [33]:
seg_list = jieba.cut('这是一个分词的例子')
result = ' '.join(seg_list)

In [34]:
result

'这是 一个 分词 的 例子'

In [35]:
import jieba.posseg as pseg
words=pseg.cut("对这句话进行分词")

## Test

In [38]:
corpus = []
with open('file/corpus/cut_corpus_of_rumor.txt', 'r') as src:
    lines = src.readlines()
    for line in lines:
        corpus.append(line)
    print('The size of corpus is {}'.format(len(corpus)))

    vectorizer = CountVectorizer()
    transformer = TfidfTransformer()
    tf_idf = transformer.fit_transform(vectorizer.fit_transform(corpus))
    vocabulary = vectorizer.get_feature_names()

The size of corpus is 34611


In [51]:
tf_idf.shape

(34611, 47938)

In [97]:
def cosine_similarity(vec_a, vec_b):
    return float(vec_a.dot(vec_b) / (np.linalg.norm(vec_a) * np.linalg.norm(vec_b)))

In [81]:
vec_shape = tf_idf[0].shape
cos = cosine_similarity(tf_idf[0].toarray(), tf_idf[1].toarray().reshape((vec_shape[1], vec_shape[0])))

In [58]:
tf_idf[0].toarray().shape

(1, 47938)

In [59]:
tf_idf[1].toarray().shape

(1, 47938)

In [82]:
tf_idf[0].toarray()

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [116]:
from sklearn import preprocessing

vec_shape = tf_idf[0].shape
vec_a = tf_idf[28].toarray()
vec_b = tf_idf[29].toarray()

In [103]:
a = preprocessing.normalize(vec_a, norm='l2')
b = preprocessing.normalize(vec_b, norm='l2')

In [106]:
cosine_similarity(a, b.reshape((vec_shape[1], vec_shape[0])))

0.8304770811557531

In [109]:
tf_idf_array = tf_idf.toarray()

In [111]:
tf_idf_array.shape

(34611, 47938)

In [112]:
tf_idf_array[0].shape

(47938,)

In [113]:
a = [[1,2,3],[3,2,1]]
b = np.array(a)

In [117]:
b = preprocessing.normalize(b, norm='l2')

In [118]:
b

array([[ 0.26726124,  0.53452248,  0.80178373],
       [ 0.80178373,  0.53452248,  0.26726124]])